### ISSUE TITLE
Allow more character types in JSON fields

### ISSUE THREAD

**Issue by martinjoconnor** [metadatacenter/cedar-model-validation-library#36]
Currently we are too restrictive on the names of fields that are output in our instance JSON. We need to allow additional characters.

Modify model validator and front end to allow these characters.

Important to meet user requirements for specific names of JSON fields (e.g., ImmPort).

**Comment by johardi** [comment]
Closes via https://github.com/metadatacenter/cedar-model-validation-library/commit/0091cf34b1dba87caa76bd24482339a9bd035269

**Comment by johardi** [comment]
I did new changes to the character restrictions:
1. Using forward slash `/` is prohibited because the model-validator uses the character in JSON path. (via https://github.com/metadatacenter/cedar-model-validation-library/commit/5caaeb524b0446660fa478e3416ae6d7a9875c86)
2. Having numbers at the beginning of the name is allowed because CEDAR can generate the names with numbers at the beginning. (via https://github.com/metadatacenter/cedar-model-validation-library/commit/12cdf555832b352728f0c27768438fa566542158)
